export const actions = {
  ADD_SELECTED_VALUE: 'ADD_SELECTED_VALUE',
  DELETE_LAST_VALUE: 'DELETE_LAST_VALUE',
  CALCULATE_RESULT: 'CALCULATE_RESULT',
  SELECT_CALCULATION: 'SELECT_CALCULATION',
  RESET: 'RESET',
  RESET_ALL: 'RESET_ALL',
};
